In [2]:
from tensorflow.keras.preprocessing.text import one_hot

ModuleNotFoundError: No module named 'tensorflow'

In [ ]:
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]


In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
##define the vocalbulary size
voc_sie = 10000

In [ ]:
one_hot_repr=[one_hot(word,voc_sie)for word in sent]
one_hot_repr

[[467, 1567, 8512, 8458],
 [467, 1567, 8512, 1418],
 [467, 4631, 8512, 1917],
 [7841, 3109, 3774, 7195, 2604],
 [7841, 3109, 3774, 7195, 1107],
 [978, 467, 8568, 8512, 4359],
 [9029, 605, 1656, 7195]]

In [ ]:
##word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential


In [ ]:
import numpy as np


In [ ]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, maxlen=sent_length, padding='pre')
embedded_docs

array([[   0,    0,    0,    0,  467, 1567, 8512, 8458],
       [   0,    0,    0,    0,  467, 1567, 8512, 1418],
       [   0,    0,    0,    0,  467, 4631, 8512, 1917],
       [   0,    0,    0, 7841, 3109, 3774, 7195, 2604],
       [   0,    0,    0, 7841, 3109, 3774, 7195, 1107],
       [   0,    0,    0,  978,  467, 8568, 8512, 4359],
       [   0,    0,    0,    0, 9029,  605, 1656, 7195]], dtype=int32)

In [ ]:
## feature representtation
dim = 10
model=Sequential()
model.add(Embedding(voc_sie,dim,input_length=sent_length))
model.compile('adam','mse')


d:\krish naik aiml ds\Moive review DL\.venv\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 319ms/step


array([[[-0.03364672, -0.00442303, -0.01128566,  0.00258968,
          0.00824673, -0.03559441,  0.0344559 , -0.04704073,
          0.00428911,  0.04410279],
        [-0.03364672, -0.00442303, -0.01128566,  0.00258968,
          0.00824673, -0.03559441,  0.0344559 , -0.04704073,
          0.00428911,  0.04410279],
        [-0.03364672, -0.00442303, -0.01128566,  0.00258968,
          0.00824673, -0.03559441,  0.0344559 , -0.04704073,
          0.00428911,  0.04410279],
        [-0.03364672, -0.00442303, -0.01128566,  0.00258968,
          0.00824673, -0.03559441,  0.0344559 , -0.04704073,
          0.00428911,  0.04410279],
        [ 0.03725458,  0.00292902,  0.0041245 ,  0.01439762,
         -0.03483722,  0.02113113, -0.0467312 ,  0.02546873,
         -0.01805263,  0.04523681],
        [-0.03618469,  0.01410473,  0.00038467,  0.03026709,
          0.03466735, -0.03360107, -0.00849328, -0.02461623,
          0.02020985, -0.03112022],
        [-0.04921222,  0.01764894,  0.02257133, -0.0

In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0,  467, 1567, 8512, 8458], dtype=int32)

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>